#!/usr/bin/env python

import gevent.monkey
gevent.monkey.patch_all (thread=False)
import os, sys
from lexer import *
from parser import *
from runner import *
from runtime import *

def main ():
	lexer = Lexer ("<stdin>", sys.stdin.read())
	parser = Parser ()
	ast = parser.parse (lexer)
	runtime = Runtime ()
	scope = Scope.base (runtime)
	runner = Runner ()
	result = runner.run (ast, scope)
	runtime.printS (result)

if __name__ == '__main__':
	main ()