#!/usr/bin/env python

# This file is part of SM (Stream Manipulator).
#
# SM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# SM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with SM.  If not, see <http://www.gnu.org/licenses/>.

import gevent.monkey
gevent.monkey.patch_all (thread=False)
import os, sys
from lexer import *
from parser import *
from runner import *
from runtime import *

def main ():
	lexer = Lexer ("<stdin>", sys.stdin.read())
	parser = Parser ()
	ast = parser.parse (lexer)
	runtime = Runtime ()
	scope = Scope.base (runtime)
	runner = Runner ()
	result = runner.run (ast, scope)
	runtime.printS (result)

if __name__ == '__main__':
	main ()